
import React, { useState, useEffect } from 'react';
import ImageUpload from './ImageUpload';
import PositionSelector from './PositionSelector';
import ReferenceManager from './ReferenceManager';
import { SubjectPosition, HistoryItem, ReferenceItem, GenerationAttributes, GeneratorMode, AppSection, ColorPalette } from '../types';
import { generateBackground, refineImage, reframeImageForTextLayout } from '../services/geminiService';
import { uploadImageToStorage } from '../services/storageService';
import { saveGeneration, getProjectHistory } from '../services/databaseService';
import { useAuth } from './AuthContext';

interface GeneratorWorkspaceProps {
    mode: GeneratorMode;
    section: AppSection;
    initialPrompt?: string;
    initialReference?: File;
    initialStyleReference?: File;
    initialGeneratorMode?: GeneratorMode;
    initialSecondaryElements?: File[];
    isActive: boolean;
    setHasKey: (hasKey: boolean) => void;
    onAddToGlobalHistory: (item: HistoryItem) => void;
    checkConcurrencyLimit: () => boolean;
    onGenerationStart: () => void;
    onGenerationEnd: () => void;
    projectId?: string;
    shouldAutoGenerate?: boolean;
    isOptimistic?: boolean;
}

const GeneratorWorkspace: React.FC<GeneratorWorkspaceProps> = ({
    mode: defaultMode,
    section,
    initialPrompt,
    initialReference,
    initialStyleReference,
    initialGeneratorMode,
    initialSecondaryElements,
    isActive,
    setHasKey,
    onAddToGlobalHistory,
    checkConcurrencyLimit,
    onGenerationStart,
    onGenerationEnd,
    projectId,
    shouldAutoGenerate,
    isOptimistic
}) => {
    const { user } = useAuth();

    // Initialize mode from prop if available, otherwise default
    const [currentMode, setCurrentMode] = useState<GeneratorMode>(initialGeneratorMode || defaultMode);

    const [userPrompt, setUserPrompt] = useState(initialPrompt || '');

    // ... (rest of state)

    // Auto-generate effect
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    useEffect(() => {
        if (shouldAutoGenerate && !hasAutoGenerated && userPrompt && !isOptimistic) {
            // Check if we are waiting for images to be processed
            const waitingForReference = initialReference && userImages.length === 0;
            const waitingForStyle = initialStyleReference && referenceItems.length === 0;
            const waitingForAssets = initialSecondaryElements && initialSecondaryElements.length > 0 && assetImages.length < initialSecondaryElements.length;

            if (!waitingForReference && !waitingForStyle && !waitingForAssets) {
                // All resources loaded, trigger generation
                handleGenerate();
                setHasAutoGenerated(true);
            }
        }
    }, [shouldAutoGenerate, hasAutoGenerated, userPrompt, userImages, referenceItems, assetImages, initialReference, initialStyleReference, initialSecondaryElements, isOptimistic]);

    const addToHistory = (url: string, promptUsed: string) => {
        const newItem: HistoryItem = {
            id: Date.now().toString() + Math.random().toString(),
            url,
            prompt: promptUsed,
            timestamp: Date.now(),
            mode: currentMode,
            section: section
        };
        setLocalHistory(prev => [newItem, ...prev]);
        onAddToGlobalHistory(newItem);
    };

    const restoreFromHistory = (item: HistoryItem) => {
        setGeneratedImage(item.url);
        // Optional: Restore prompt as well
        if (item.prompt && !item.prompt.includes("Auto-generated")) {
            setUserPrompt(item.prompt);
        }
    };

    const toggleHistorySelection = (id: string) => {
        setSelectedHistoryIds(prev =>
            prev.includes(id) ? prev.filter(hid => hid !== id) : [...prev, id]
        );
    };

    const handleMerge = () => {
        const selectedItems = localHistory.filter(item => selectedHistoryIds.includes(item.id));
        const imagesToMerge = selectedItems.map(item => item.url.split(',')[1]); // get base64

        // Load selected images as input User Images
        setUserImages(imagesToMerge);
        setUserPrompt("Mesclar estas imagens em uma nova composição harmoniosa. [Adicione detalhes...]");
        setReferenceItems([]); // Clear references to focus on merge? Or keep them.

        // Clear selection
        setSelectedHistoryIds([]);
    };

    const getModeLabel = () => {
        switch (currentMode) {
            case 'HUMAN': return 'Pessoas (Sujeito)';
            case 'OBJECT': return 'Objeto/Produto';
            case 'ENHANCE': return 'Imagem Original';
            case 'INFOPRODUCT': return 'Expert (Infoproduto)';
            default: return 'Sujeito';
        }
    };

    const getUploadLabel = () => {
        switch (currentMode) {
            case 'HUMAN': return 'Fotos da Pessoa';
            case 'OBJECT': return 'Fotos do Objeto';
            case 'ENHANCE': return 'Imagem Base para Melhorar';
            case 'INFOPRODUCT': return 'Foto do Expert';
            default: return 'Imagens';
        }
    };

    const getUploadDesc = () => {
        switch (currentMode) {
            case 'HUMAN': return "Envie fotos para fidelidade facial.";
            case 'OBJECT': return "Envie fotos do produto em alta resolução.";
            case 'ENHANCE': return "A imagem original será mantida, mas enriquecida.";
            case 'INFOPRODUCT': return "O sistema melhorará pose/roupa se necessário, mantendo o rosto.";
            default: return "";
        }
    };

    const handleGenerate = async () => {
        if (userImages.length === 0) {
            setError(currentMode === 'ENHANCE' ? "Envie a imagem que deseja melhorar." : "Por favor, envie pelo menos uma foto do sujeito.");
            return;
        }

        if (!checkConcurrencyLimit()) {
            setError("Limite de gerações simultâneas atingido (Max 2). Aguarde uma terminar.");
            return;
        }

        setIsGenerating(true);
        setError(null);
        setGeneratedImage(null);
        onGenerationStart();

        try {
            // BATCH GENERATION LOGIC
            const requests = [];
            for (let i = 0; i < batchSize; i++) {
                const variationNoise = batchSize > 1 ? ` (Variation ${i + 1}: slightly vary lighting details)` : "";
                const effectivePrompt = userPrompt + variationNoise;

                requests.push(
                    generateBackground(
                        section,
                        currentMode,
                        userImages,
                        referenceItems,
                        assetImages,
                        effectivePrompt,
                        position,
                        attributes,
                        customHeight,
                        currentMode === 'INFOPRODUCT' ? colorPalette : undefined
                    )
                );
            }

            const results = await Promise.allSettled(requests);

            const successResults = results.filter(r => r.status === 'fulfilled') as PromiseFulfilledResult<{ image: string, finalPrompt: string }>[];
            const failResults = results.filter(r => r.status === 'rejected') as PromiseRejectedResult[];

            if (successResults.length > 0) {
                setGeneratedImage(successResults[0].value.image);

                // Save to Supabase if logged in
                if (user) {
                    for (const res of successResults) {
                        const publicUrl = await uploadImageToStorage(res.value.image, user.id);
                        if (publicUrl) {
                            // Update Main View to WebP if this is the first image
                            if (res === successResults[0]) {
                                setGeneratedImage(publicUrl);
                            }

                            const savedItem = await saveGeneration(
                                user.id,
                                publicUrl,
                                res.value.finalPrompt,
                                currentMode,
                                section,
                                projectId
                            );
                            if (savedItem) {
                                addToHistory(publicUrl, res.value.finalPrompt);
                            }
                        } else {
                            // Fallback local
                            addToHistory(res.value.image, res.value.finalPrompt);
                        }
                    }
                } else {
                    successResults.forEach(res => {
                        addToHistory(res.value.image, res.value.finalPrompt);
                    });
                }
            }

            if (failResults.length > 0) {
                const errMsg = failResults[0].reason?.message || "Erro desconhecido";
                if (errMsg.includes("Requested entity was not found")) {
                    setError("Chave de API inválida ou expirada.");
                    setHasKey(false);
                } else {
                    setError(`Algumas gerações falharam: ${errMsg} `);
                }
            }

        } catch (err: any) {
            setError(err.message || "Ocorreu um erro inesperado.");
        } finally {
            setIsGenerating(false);
            onGenerationEnd();
        }
    };

    const handleRefine = async () => {
        if (!generatedImage || !refinePrompt) return;

        if (!checkConcurrencyLimit()) {
            setError("Limite de gerações simultâneas atingido (Max 2).");
            return;
        }

        setIsGenerating(true);
        setError(null);
        onGenerationStart();

        try {
            const result = await refineImage(generatedImage, refinePrompt, refineAssets);
            setGeneratedImage(result);
            addToHistory(result, `Ajuste: ${refinePrompt} `);
            setRefinePrompt('');
            setRefineAssets([]);
        } catch (err: any) {
            setError(err.message || "Falha ao refinar imagem.");
        } finally {
            setIsGenerating(false);
            onGenerationEnd();
        }
    };

    const handleValidateAndFormat = async () => {
        if (!generatedImage) return;

        if (!checkConcurrencyLimit()) {
            setError("Limite de gerações simultâneas atingido (Max 2).");
            return;
        }

        setIsGenerating(true);
        setError(null);
        onGenerationStart();

        try {
            const result = await reframeImageForTextLayout(generatedImage, verticalHeight, verticalPrompt);
            setGeneratedImage(result);
            addToHistory(result, `Formato Vertical(${verticalHeight}px) - ${verticalPrompt || 'Padrão'} `);
        } catch (err: any) {
            setError(err.message || "Falha ao formatar imagem.");
        } finally {
            setIsGenerating(false);
            onGenerationEnd();
        }
    };

    const toggleAttribute = (key: keyof GenerationAttributes) => {
        setAttributes(prev => ({ ...prev, [key]: !prev[key] }));
    };

    const handleDownload = async (url: string) => {
        try {
            const response = await fetch(url);
            const blob = await response.blob();
            const blobUrl = window.URL.createObjectURL(blob);

            const link = document.createElement('a');
            link.href = blobUrl;
            link.download = `design - builder - ${Date.now()}.webp`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            window.URL.revokeObjectURL(blobUrl);
        } catch (error) {
            console.error('Download failed:', error);
            window.open(url, '_blank');
        }
    };

    return (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 animate-fadeIn h-full overflow-hidden" style={{ display: isActive ? 'grid' : 'none' }}>

            {/* LEFT PANEL: CONTROLS (FIXED FOOTER LAYOUT) */}
            <div className="lg:col-span-4 h-full flex flex-col relative bg-white/60 dark:bg-gray-900/40 backdrop-blur-xl border-r border-gray-200 dark:border-white/5 rounded-l-2xl overflow-hidden transition-colors duration-300">

                {/* Scrollable Content */}
                <div className="flex-1 overflow-y-auto pr-2 pb-6 scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-700 p-6 space-y-6">

                    {/* Image Inputs */}
                    <div className="bg-gray-50 dark:bg-gray-900/60 border border-gray-200 dark:border-white/5 rounded-2xl p-6 shadow-sm">
                        <h2 className="text-lg font-semibold mb-4 flex items-center gap-2 text-gray-900 dark:text-white/90">
                            <i className={`fas ${currentMode === 'HUMAN' ? 'fa-user' : currentMode === 'OBJECT' ? 'fa-cube' : currentMode === 'INFOPRODUCT' ? 'fa-chalkboard-teacher' : 'fa-wand-magic'} text-lime-600 dark:text-lime-400`}></i>
                            {getModeLabel()}
                        </h2>
                        <ImageUpload
                            label={getUploadLabel()}
                            value={userImages}
                            onChange={setUserImages}
                            multiple={true}
                            description={getUploadDesc()}
                        />

                        <ReferenceManager
                            items={referenceItems}
                            onChange={setReferenceItems}
                        />

                        <ImageUpload
                            label={currentMode === 'INFOPRODUCT' ? "Elementos 3D / Ícones (Flutuantes)" : "Elementos Secundários"}
                            value={assetImages}
                            onChange={setAssetImages}
                            multiple={true}
                            description={currentMode === 'INFOPRODUCT' ? "Serão desfocados no fundo (Ex: moedas, gráficos)." : "Logotipos ou elementos extras."}
                        />
                    </div>

                    {/* Configuration */}
                    <div className="bg-gray-50 dark:bg-gray-900/60 border border-gray-200 dark:border-white/5 rounded-2xl p-6 shadow-sm">
                        <h2 className="text-lg font-semibold mb-4 flex items-center gap-2 text-gray-900 dark:text-white/90">
                            <i className="fas fa-sliders-h text-lime-600 dark:text-lime-400"></i> Configuração
                        </h2>

                        <PositionSelector value={position} onChange={setPosition} />

                        {/* INFOPRODUCT COLOR PALETTE */}
                        {currentMode === 'INFOPRODUCT' && (
                            <div className="mb-6 space-y-3 border-t border-gray-200 dark:border-white/5 py-4">
                                <h3 className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2">Paleta de Cores e Luz</h3>

                                <div>
                                    <label className="block text-xs text-gray-500 mb-1">Fundo (Predominante)</label>
                                    <input
                                        type="text"
                                        placeholder="Ex: Preto Luxo, Azul Marinho..."
                                        value={colorPalette.primary}
                                        onChange={(e) => setColorPalette(prev => ({ ...prev, primary: e.target.value }))}
                                        className="w-full bg-white dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded px-2 py-1.5 text-sm text-gray-900 dark:text-white focus:border-lime-500 outline-none"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs text-gray-500 mb-1">Luz de Recorte (Profundidade)</label>
                                    <input
                                        type="text"
                                        placeholder="Ex: Dourado, Ciano, Branco Frio..."
                                        value={colorPalette.secondary}
                                        onChange={(e) => setColorPalette(prev => ({ ...prev, secondary: e.target.value }))}
                                        className="w-full bg-white dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded px-2 py-1.5 text-sm text-gray-900 dark:text-white focus:border-lime-500 outline-none"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs text-gray-500 mb-1">Detalhes (Overlays/Partículas)</label>
                                    <input
                                        type="text"
                                        placeholder="Ex: Verde Neon, Laranja..."
                                        value={colorPalette.accent}
                                        onChange={(e) => setColorPalette(prev => ({ ...prev, accent: e.target.value }))}
                                        className="w-full bg-white dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded px-2 py-1.5 text-sm text-gray-900 dark:text-white focus:border-lime-500 outline-none"
                                    />
                                </div>
                            </div>
                        )}

                        {/* Attributes Toggles */}
                        <div className="mb-6 grid grid-cols-2 gap-3">
                            <button
                                onClick={() => toggleAttribute('useGradient')}
                                className={`flex items-center justify-center gap-2 p-3 rounded-lg border text-sm font-medium transition-all ${attributes.useGradient
                                    ? 'bg-lime-500/10 border-lime-500 text-lime-600 dark:text-lime-400'
                                    : 'bg-white dark:bg-black/40 border-gray-300 dark:border-gray-700 text-gray-500 dark:text-gray-400'
                                    } `}
                            >
                                <i className={`fas ${attributes.useGradient ? 'fa-check-square' : 'fa-square'} `}></i>
                                Degradê (Fade)
                            </button>
                            <button
                                onClick={() => toggleAttribute('useBlur')}
                                className={`flex items-center justify-center gap-2 p-3 rounded-lg border text-sm font-medium transition-all ${attributes.useBlur
                                    ? 'bg-lime-500/10 border-lime-500 text-lime-600 dark:text-lime-400'
                                    : 'bg-white dark:bg-black/40 border-gray-300 dark:border-gray-700 text-gray-500 dark:text-gray-400'
                                    } `}
                            >
                                <i className={`fas ${attributes.useBlur ? 'fa-check-square' : 'fa-square'} `}></i>
                                Blur (Rack Focus)
                            </button>
                        </div>

                        {/* Dimensions Input */}
                        <div className="mb-4 grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Largura (px)</label>
                                <input
                                    type="number"
                                    value={1920}
                                    disabled
                                    className="w-full bg-gray-100 dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded-lg px-3 py-2 text-gray-500 text-sm cursor-not-allowed"
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Altura (px)</label>
                                <input
                                    type="number"
                                    value={customHeight}
                                    onChange={(e) => setCustomHeight(Number(e.target.value))}
                                    className="w-full bg-white dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded-lg px-3 py-2 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-lime-500 outline-none"
                                    min={500}
                                    max={2160}
                                />
                            </div>
                        </div>

                        <div className="mb-4">
                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                {currentMode === 'ENHANCE' ? 'Instruções de Melhoria' : 'Prompt do Cenário'}
                            </label>
                            <textarea
                                value={userPrompt}
                                onChange={(e) => setUserPrompt(e.target.value)}
                                placeholder={
                                    currentMode === 'ENHANCE'
                                        ? "Descreva o que melhorar..."
                                        : currentMode === 'INFOPRODUCT'
                                            ? "Descreva o nicho (ex: Mentor financeiro, Curso de inglês) e a atmosfera desejada..."
                                            : "Descreva o cenário..."
                                }
                                className="w-full bg-white dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded-xl p-3 text-sm text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-600 focus:ring-2 focus:ring-lime-500 focus:border-transparent outline-none transition-all min-h-[100px]"
                            />
                        </div>
                    </div>

                    {/* Spacer to prevent content being hidden behind footer */}
                    <div className="h-48"></div>
                </div>

                {/* Sticky Footer */}
                <div className="absolute bottom-0 left-0 right-0 bg-white/95 dark:bg-gray-900/95 backdrop-blur-xl border-t border-gray-200 dark:border-white/10 p-4 z-20 shadow-[0_-10px_40px_rgba(0,0,0,0.1)] dark:shadow-[0_-10px_40px_rgba(0,0,0,0.5)]">
                    {/* BATCH SELECTOR */}
                    <div className="flex items-center justify-between mb-4 px-1">
                        <span className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider">Quantidade:</span>
                        <div className="flex gap-3 bg-gray-100 dark:bg-black/40 p-1.5 rounded-xl border border-gray-300 dark:border-gray-700">
                            {[1, 2, 3, 4].map(num => (
                                <button
                                    key={num}
                                    onClick={() => setBatchSize(num)}
                                    className={`w-10 h-10 rounded-lg text-base font-bold transition-all ${batchSize === num ? 'bg-lime-500 text-black shadow-lg scale-105' : 'text-gray-500 hover:text-gray-900 dark:hover:text-white hover:bg-white/50 dark:hover:bg-white/10'
                                        } `}
                                >
                                    {num}x
                                </button>
                            ))}
                        </div>
                    </div>

                    <button
                        onClick={handleGenerate}
                        disabled={isGenerating || userImages.length === 0}
                        className={`
w-full py-4 px-6 rounded-xl font-bold text-lg shadow-xl flex items-center justify-center gap-2
transition-all duration-300 transform hover:scale-[1.01] active:scale-95
                        ${isGenerating || userImages.length === 0
                                ? 'bg-gray-200 dark:bg-gray-800 text-gray-400 dark:text-gray-500 cursor-not-allowed border border-gray-300 dark:border-gray-700'
                                : 'bg-gradient-to-r from-lime-500 to-lime-600 hover:from-lime-400 hover:to-lime-500 text-white dark:text-gray-900 border border-lime-400'
                            }
`}
                    >
                        {isGenerating ? (
                            <>
                                <i className="fas fa-circle-notch fa-spin"></i> Processando...
                            </>
                        ) : (
                            <>
                                <i className="fas fa-wand-magic-sparkles"></i> {currentMode === 'ENHANCE' ? 'Melhorar' : 'Gerar'}
                            </>
                        )}
                    </button>
                    {error && (
                        <div className="mt-2 p-2 text-center text-xs text-red-500 dark:text-red-400 bg-red-100 dark:bg-red-500/10 rounded">
                            <i className="fas fa-exclamation-triangle mr-1"></i> {error}
                        </div>
                    )}
                </div>
            </div>

            {/* RIGHT PANEL: PREVIEW & HISTORY */}
            <div className="lg:col-span-8 flex flex-col h-full overflow-hidden">

                {/* Main Preview */}
                <div className="bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl border border-gray-200 dark:border-white/5 rounded-2xl p-1 shadow-2xl flex-grow relative overflow-hidden group mb-4 min-h-[400px]">
                    {generatedImage ? (
                        <div className="relative w-full h-full flex flex-col items-center justify-center bg-gray-100 dark:bg-black/20 rounded-xl overflow-hidden">
                            <img
                                src={generatedImage}
                                alt="Generated Background"
                                className="max-w-full max-h-full object-contain shadow-2xl"
                            />
                            <div className="absolute top-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                <button
                                    onClick={() => handleDownload(generatedImage)}
                                    className="bg-white/80 dark:bg-black/60 hover:bg-lime-500 hover:text-black text-gray-900 dark:text-white p-3 rounded-lg backdrop-blur-md border border-gray-200 dark:border-white/10 transition-colors"
                                    title="Baixar Imagem"
                                >
                                    <i className="fas fa-download"></i>
                                </button>
                            </div>

                            {/* Validation Actions Overlay */}
                            {!isGenerating && (
                                <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 w-full max-w-2xl px-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                    <div className="bg-white/90 dark:bg-black/80 backdrop-blur-md border border-gray-200 dark:border-white/10 rounded-2xl p-3 flex flex-col sm:flex-row items-center gap-4 shadow-2xl">
                                        <div className="flex-1 w-full">
                                            <input
                                                type="text"
                                                value={verticalPrompt}
                                                onChange={(e) => setVerticalPrompt(e.target.value)}
                                                placeholder="Prompt Vertical (Opcional)"
                                                className="w-full bg-transparent border-b border-gray-400 dark:border-gray-600 px-3 py-2 text-xs text-gray-900 dark:text-white focus:border-lime-500 outline-none"
                                            />
                                        </div>
                                        <div className="flex items-center gap-2 pl-4">
                                            <div className="flex items-center gap-1">
                                                <span className="text-xs text-gray-500">H:</span>
                                                <input
                                                    type="number"
                                                    value={verticalHeight}
                                                    onChange={(e) => setVerticalHeight(Number(e.target.value))}
                                                    className="w-14 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded text-xs px-1 py-1 text-gray-900 dark:text-white text-center"
                                                />
                                            </div>
                                            <button
                                                onClick={handleValidateAndFormat}
                                                className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded-lg text-xs font-bold transition-colors whitespace-nowrap"
                                            >
                                                <i className="fas fa-mobile-alt"></i> Formatar 9:16
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-gray-600 bg-gray-50 dark:bg-black/20 rounded-xl">
                            {isGenerating ? (
                                <div className="text-center">
                                    <div className="inline-block w-16 h-16 border-4 border-lime-500/30 border-t-lime-500 rounded-full animate-spin mb-4"></div>
                                    <p className="text-lime-600 dark:text-lime-400 animate-pulse font-medium">Renderizando com Gemini...</p>
                                </div>
                            ) : (
                                <div className="text-center p-8">
                                    <i className={`fas ${currentMode === 'HUMAN' ? 'fa-user-circle' : currentMode === 'OBJECT' ? 'fa-cube' : currentMode === 'INFOPRODUCT' ? 'fa-chalkboard-teacher' : 'fa-wand-magic'} text-6xl mb-4 text-gray-300 dark:text-gray-800`}></i>
                                    <p className="text-xl font-medium text-gray-400 dark:text-gray-500">
                                        {currentMode === 'ENHANCE' ? 'Melhorar Imagem' : currentMode === 'INFOPRODUCT' ? 'Criar Infoproduto' : `Criar ${currentMode === 'HUMAN' ? 'Pessoa' : 'Objeto'} `}
                                    </p>
                                </div>
                            )}
                        </div>
                    )}
                </div>

                {/* Refinement Section */}
                {generatedImage && !isGenerating && (
                    <div className="bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl border border-gray-200 dark:border-white/5 rounded-2xl p-4 shadow-lg animate-fadeIn mb-4">
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2 flex justify-between">
                            <span><i className="fas fa-sliders-h mr-2 text-lime-600 dark:text-lime-400"></i>Ajustes Finos</span>
                        </label>
                        <div className="flex flex-col gap-3">
                            <div className="flex gap-2 items-start">
                                <div className="w-24">
                                    <ImageUpload
                                        label=""
                                        value={refineAssets}
                                        onChange={setRefineAssets}
                                        multiple={true}
                                        description=""
                                    />
                                </div>
                                <div className="flex-1 flex gap-2">
                                    <input
                                        type="text"
                                        value={refinePrompt}
                                        onChange={(e) => setRefinePrompt(e.target.value)}
                                        placeholder="Ex: 'Deixe a luz mais quente'..."
                                        className="flex-1 bg-white dark:bg-black/40 border border-gray-300 dark:border-gray-700 rounded-xl px-4 py-2 text-sm focus:ring-2 focus:ring-lime-500 outline-none h-12 text-gray-900 dark:text-white"
                                        onKeyDown={(e) => e.key === 'Enter' && handleRefine()}
                                    />
                                    <button
                                        onClick={handleRefine}
                                        disabled={!refinePrompt}
                                        className="bg-gray-200 hover:bg-gray-300 dark:bg-gray-800 dark:hover:bg-gray-700 text-gray-900 dark:text-white px-4 rounded-xl text-sm font-medium transition-colors disabled:opacity-50 h-12 border border-gray-300 dark:border-gray-700"
                                    >
                                        Refinar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                )}

                {/* Local History Strip */}
                {localHistory.length > 0 && (
                    <div className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-xl border border-gray-200 dark:border-white/5 rounded-t-2xl p-4 flex flex-col mt-auto shadow-[0_-5px_20px_rgba(0,0,0,0.1)] dark:shadow-[0_-5px_20px_rgba(0,0,0,0.5)]">
                        <div className="flex items-center justify-between mb-2">
                            <h3 className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider flex items-center gap-2">
                                <i className="fas fa-history"></i> Histórico da Aba
                            </h3>
                            {selectedHistoryIds.length > 0 && (
                                <button
                                    onClick={handleMerge}
                                    className="text-xs bg-lime-500 hover:bg-lime-400 text-black px-3 py-1 rounded font-bold transition-colors"
                                >
                                    <i className="fas fa-object-group mr-1"></i> Mesclar Selecionados ({selectedHistoryIds.length})
                                </button>
                            )}
                        </div>
                        <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-700 h-28 items-center">
                            {localHistory.map(item => {
                                const isSelected = selectedHistoryIds.includes(item.id);
                                return (
                                    <div
                                        key={item.id}
                                        className={`relative flex-shrink-0 h-24 aspect-[16/9] rounded-lg overflow-hidden border-2 cursor-pointer transition-all group ${isSelected ? 'border-lime-500 ring-2 ring-lime-500/30' : 'border-gray-200 dark:border-gray-700 hover:border-gray-400 dark:hover:border-gray-500'} `}
                                        onClick={() => restoreFromHistory(item)}
                                    >
                                        <img src={item.url} alt="Histórico" className="w-full h-full object-cover" />

                                        {/* Hover Info */}
                                        <div className="absolute inset-0 bg-black/80 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-center items-center p-2 text-center">
                                            <p className="text-[10px] text-gray-300 line-clamp-2 mb-1">{item.prompt || 'Sem prompt'}</p>
                                            <span className="text-[10px] text-lime-400 font-bold">Clique para Restaurar</span>
                                        </div>

                                        {/* Select Checkbox */}
                                        <div
                                            className="absolute top-1 left-1 z-10"
                                            onClick={(e) => { e.stopPropagation(); toggleHistorySelection(item.id); }}
                                        >
                                            <div className={`w-4 h-4 rounded border ${isSelected ? 'bg-lime-500 border-lime-500' : 'bg-white/50 dark:bg-black/50 border-gray-400'} flex items-center justify-center`}>
                                                {isSelected && <i className="fas fa-check text-[10px] text-black"></i>}
                                            </div>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default GeneratorWorkspace;